#
#	Makefile for tests subdirectory
#
# 060920 Bruce Jackson, NASA Langley Research Center
#                      <mailto:e.b.jackson@larc.nasa.gov>  

HOME   = /Users/bjax

make: test

all: test

test: 
#	cd unit_tests && $(MAKE) test
	cd app-tests && $(MAKE) test

clean: 
#	cd unit_tests && $(MAKE) clean
	cd app-tests && $(MAKE) clean

realclean:
#	cd unit_tests && $(MAKE) realclean
	cd app-tests && $(MAKE) realclean

.PHONY: test clean realclean


